### ISSUE TITLE
What is the format of the parameter been sent? 

### ISSUE THREAD

**Issue by ErogeXiao** [realbadidas/Arma-Remote-Code-Executor#2]
I'm totally new to this, can you make an example for this addon? Much appreciate!!!

**Comment by realbadidas** [comment]
After you have edited your config and uploaded it to your server, you need to make a post request to your specified port (default: 6601). You can use cURL or html combined with javascript to send this, or just google devtools :3

If you use cURL, you can just execute this:
`curl -X POST -F 'user=YourUsername' -F 'pass=YourPassword' -F 'execute=YourCode' http://YourServerIp:Port/send
`
If you use a self signed certificate you may want to add the insecure option.

If you have any more questions, feel free to just ask.

**Comment by realbadidas** [comment]
Closed due to inactivity.
