### ISSUE TITLE
Parameter werden nicht übernommen

### ISSUE THREAD

**Issue by DiePfeiffe** [realbadidas/Arma-Remote-Code-Executor#3]
Hallo,

leider bin ich beim Testen dieses Projektes auf ein "kleines" Problem gestoßen.
Das Starten des Servers verläuft problemlos, es öffnet sich auch das Konsolenfenster der Erweiterung.
Die Config habe ich mit Standardwerten belassen, lediglich  https habe ich deaktivert und den Pfad der Zertifikate habe ich das Backslash durch ein Slash ersetzt, da dies das Starten verhinderte.
<details>
<summary>config.json</summary>
{

	"host": "127.0.0.1",
	"port": "6601",
	
	
	"https": "false",
	
	"SSL_Key": "@sqfremoteexecute/ssl.key",
	"SSL_Cert": "@sqfremoteexecute/ssl.cert",
	
	
	"users": [
			{
				"user": "foo",
				"pass": "fcde2b2edba56bf408601fb721fe9b5c338d10ee429ea04fae5511b68fbf8fb9"
			}
	]
}
</details>

Wenn ich nun per Postman oder curl einen Post Request an den Server sende fehlen in der Antwort jegliche Inhalte
Request: `curl -X POST -F 'user=foo' -F 'pass=bar' -F 'execute=diag_log(str(1337));' http://127.0.0.1:6601/send` 
Antwort: `{"code":"3","return":"Access denied for @e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}`

Es fehlt also der gesamte Inhalt des Request, obwohl dieser (meiner Meinung nach richtig) übergeben wird. 
Im rpt ist ebenfalls kein Fehler auffällig.

![Übersicht](https://img.pfeifferserver.de/i/9ec9586d-23fc-4ec0-b550-cd95e20041c9_EhxGS76lnL_SpringbokFull.png)

Zum Testen habe ich ebenfalls bereits:
- ohne Mods den Server gestartet
- den Release erneut heruntergeladen
- Lokal sowie auf dem Server getestet

Ich würde mich über eine Antwort freuen.

Mit freundlichen Grüßen
Max

If you don't understand German, it is best to use Google translator, my English is not the best.

**Comment by realbadidas** [comment]
versuch mal den header "Content-Type: application/json" zu benutzen

**Comment by realbadidas** [comment]
laut rpt wird die extension geladen, also läuft da erstmal alles richtig. außerdem bekommt man etwas zurück, der fehler liegt also irgendwo beim kommunizieren mit dem server. ich versuche gleich mal das problem zu reproduzieren.

**Comment by realbadidas** [comment]
versuch als request mal das: `curl -d "user=foo&pass=bar&execute=diag_log%28str%281337%29%29" -X POST http://127.0.0.1:6601/send`

**Comment by DiePfeiffe** [comment]
Ok, bei dem von dir geschickten wird es tatsächlich erfolgreich ausgeführt:
`curl -d "user=foo&pass=bar&execute=diag_log%28str%281337%29%29" -X POST http://127.0.0.1:6601/send`
`{"code":"0","return":"<null>"}`
 
Im RPT ist auch erkennbar, dass es erfolgreich ausgeführt wurden, es wird aber direkt ein Script-Error hinterhergeschickt
<details>
<summary>RPT</summary>
19:41:59 "New execution! | RES: diag_log(str(1337))"<br>
19:41:59 "1337"<br>
19:41:59 Error in expression <sqfexecute" callExtension format["4%1", _retam];<br>
};<br>
uiSleep 0.03;<br>
};<br>
};><br>
19:41:59   Error position: <_retam];<br>
};<br>
uiSleep 0.03;<br>
};<br>
};><br>
19:41:59   Error Undefined variable in expression: _retam<br>
19:41:59 File sqfremoteexecute\fnc_startInit.sqf..., line 32<br>
</details>

Das ursprüngliche Problem scheint also behoben zu sein, ich habe die Parameter falsch übergeben. Ein Returnwert kommt für den Request auch direkt als Response an, aber in der Konsole der Extension selbst fehlt immer noch jeglicher Inhalt.
![d7b0fc98-a388-49b6-987f-a4ffc95afbfe_CUAkY4eTSu_HumpbackwhalePalatable](https://user-images.githubusercontent.com/74821900/148109696-fe150ec3-26a0-4bb2-a58c-79e3a3bfd511.png)

Dann aber trotzdem erstmal vielen Dank für die schnelle Hilfe, auch wenn es ursprünglich quasi ein Nutzerfehler von mir bei der Parameterübergabe war.

**Comment by realbadidas** [comment]
versuch mal nen anderen befehl als diag_log, sowas wie hint oder so, bedenke aber, dass du eventuell remoteexec dafür benötigst, da das serverseitig ausgeführt wird.

**Comment by realbadidas** [comment]
ich merk grad, dass du schon andere befehle ausgeführt hast, ich weiß grad auch net wo das problem liegen könnte, ich muss mir nochmal den code anschauen den ich da vor nem jahr geschrieben hab

**Comment by realbadidas** [comment]
okay, ich habe mir den code nochmal angeschaut. im c++ code von der extension is nen obv. fehler, den kann ich aber leicht beheben, es ist nur ein fehler bei der ausgabe, der andere fehler ist im sqf code, da ich aber schon lange mit sqf aufgehört habe weiß ich selber nicht was falsch ist. 

```
thr = {
	while {true} do {
		_res = "sqfexecute" callExtension "5";
		if(_res != "no-message-yet") then {
			diag_log format["New execution! | RES: %1", _res];
			
			_retam = 0 call compile _res;
			
			"sqfexecute" callExtension format["4%1", _retam];
		};
		uiSleep 0.03;
	};
};
```

Das ist der "Thread", wenn man das so nennen kann, von dem mod. dieser looped bis jmd eine request sendet, executed und sendet den return wert zurück. vielleicht siehst du ja den fehler irgendwo.

**Comment by DiePfeiffe** [comment]
Jupp, bei Hint ist der Fehler weg. Wenn man darüber nach denkt, ergibt der Fehler auch Sinn. diag_log hat keinen Return Wert, RemoteExec schon (auch wenn es nur ein leerer String ist).
Die Konsole zeigt aber immer noch nichts an, was zwar grundsätzlich praktisch wäre, aber nicht essentiell. Ich würde ggf. eine zusätzliche Option bevorzugen, ob die Konsole als Log geöffnet werden soll, ob es in eine Datei geschrieben werden soll oder nichts. Wichtig ist dies aber auch nicht.
![273af7d9-2322-4b51-acce-46e0936946ba_nLPjYEcVeP_AlligatorsnappingturtleMintcream](https://user-images.githubusercontent.com/74821900/148113075-1b6f3320-8423-4752-b236-8bcc8e0a717f.png)

Ich bedanke mich aber gerne nochmal für die Hilfe und für das nützliche Tool!

**Comment by realbadidas** [comment]
> Die Konsole zeigt aber immer noch nichts an
> es ist nur ein fehler bei der ausgabe


die ausgabe in der konsole werd ich noch in den nächsten tagen noch fixen. das mit der konsole wegmachen in der config hatte ich schon fertig programmiert vor ein paar monaten, jedoch ist mein laptop auf dem das war kaputtgegangen, und damit auch das projekt. wenn ich mal zeit finde fixe ich das alles.

**Comment by DiePfeiffe** [comment]
`if (isNil "_retam") then { _retam = "empty return"};`
Wenn du das nach `_retam = 0 call compile _res;` packst, sollte bei einer leeren Antwort zumindest ein Script-Error verhindert werden und eine kontrollierte Antwort kommen.

**Comment by realbadidas** [comment]
> `if (isNil "_retam") then { _retam = "empty return"};` Wenn du das nach `_retam = 0 call compile _res;` packst, sollte bei einer leeren Antwort zumindest ein Script-Error verhindert werden und eine kontrollierte Antwort kommen.

jo, danke, das mach ich dann in die neuste version.

**Comment by realbadidas** [comment]
neue version kommt dieses wochenende.
