### ISSUE TITLE
TESTING on local server with postman

### ISSUE THREAD

**Issue by idracgod54** [realbadidas/Arma-Remote-Code-Executor#5]
hello i was testing this on a local server and for execution I put
markers = allMapMarkers;
markers;
and it returned 
Incoming Request
Authenticated? >> YES >> 
SCRIPT EXEC: markers = allMapMarkers;
markers;
any reason it returned this ?
CODE: 5
RETURN: NO RESPONSE FROM SCRIPT

**Comment by realbadidas** [comment]
The response to talk to the script that executes the command timed out. You have to be on the server or have autoInit on so it works.

**Comment by idracgod54** [comment]
ive tried it with autoinit as well as with players on the server an it returns code 5 still

**Comment by realbadidas** [comment]
![grafik](https://user-images.githubusercontent.com/20842620/166306185-aee2cfae-e897-4a03-b432-6f56fc4b566e.png)
your code seems to work fine on my machine, i don't really know why it is not working on yours. maybe upload your RPT logs?

**Comment by realbadidas** [comment]
there seems to be a bug though, but it doesn't seem to interfere with the execution:  the max limit of callExtension is 2048, if you have many markers (like i do, you can see it clearly in the picture at the top), it will cap after 2048 chars. but that does not explain why you are getting code 5.

**Comment by realbadidas** [comment]
that is weird maybe they block execution of code or something? you'll have to check with their support i guess

**Comment by realbadidas** [comment]
you could still send your rpt log, maybe there is something in there that could explain why it is not working when these scripts are loaded

**Comment by idracgod54** [comment]
sorry i was wrong what it turned out to be is the mission would load as well as SQFEXECUTE then an error caused the mission to reload and instead OK it would log as preventing crash and so if the extension gets called 2x it would return code 5

**Comment by realbadidas** [comment]
oh well, i thought i have fixed this bug, seems like it still isn't fixed. i will look into it.

**Comment by realbadidas** [comment]
Fixed in new release 1.1
