### ISSUE TITLE
Cant execute commands

### ISSUE THREAD

**Issue by AlanKvA1** [realbadidas/Arma-Remote-Code-Executor#6]
Hi, I'm trying to use this program but I couldn't. I just connected to the server, but I can't run any scripts. Can you put some simple tutorial with examples to run this program correctly?

Like:
curl -X POST "http://192.168.0.3:6601/send" -d "user=XXX" -d "pass=XXX" -d "execute=nul = [this] execVM "functions\Missions\fn_missionRequest.sqf""

Server LOG:
22:25:30 "New execution! | RES: nul"
22:25:30 Error in expression <nul>
22:25:30   Error position: <nul>
22:25:30   Error Undefined variable in expression: nul

Thank you so much

**Comment by realbadidas** [comment]
are you sure the script you are passing to the server is valid? because you get a response back, so it probably executed (but just with an error). can you just try to do a simple hint to test it?

btw, i don't know if this is intended, but you did not escape your quotation marks

**Comment by AlanKvA1** [comment]
Sorry im new to this... You mean like this: curl -X POST "http://192.168.0.3:6601/send" -d "user=foo" -d "pass=bar" -d "execute=nul = [this] execVM \"functions\Missions\fn_missionRequest.sqf\""

?

**Comment by realbadidas** [comment]
try this
curl -X POST "http://192.168.0.3:6601/send" -d "user=foo" -d "pass=bar" -d "execute=hint 'Test'"

then look ingame to see if it worked (a hint should appear on the upper right corner of your screen)

**Comment by AlanKvA1** [comment]
Thanks for the fast answer!

But no success... heres return of dedicated server log:

15:46:40 "New execution! | RES: hint"
15:46:40 Error in expression <hint>
15:46:40   Error position: <>
15:46:40   Error Invalid number in expression

It doesn't seem to read the whole code, just the first word.

**Comment by realbadidas** [comment]
sorry, i made a mistake.

try
curl -X POST "http://192.168.0.3:6601/send" -d "user=foo" -d "pass=bar" -d "execute=hint%20%27Test%27"

**Comment by AlanKvA1** [comment]
Your code are better, log returns:

16:38:46 "New execution! | RES: hint 'Test'"

but no hint on screen. I put the same code ( hint "Test" ) in debug console and got the hint in screen only on global exec or local exec. With Server Exec doenst work. I think to send to server its some code like this: ["Test"] remoteExec ["hint"]; I put in debug console and works with server exec.

I wrote:
curl -X POST "http://192.168.0.3:6601/send" -d "user=foo" -d "pass=bar" -d "execute=['Test']%20remoteExec%20['hint'];" 
and it works !!!

Thank you very much!!! You and your program are amazing!!!!

**Comment by AlanKvA1** [comment]
Sorry if I'm bothering you. Thank you if you can help me again. I'm trying to send curl -X POST "http://192.168.0.3:6601/send" -d "user=foo" -d "pass=bar" -d "execute=nul = [this] execVM 'Scripts\aliado.sqf';" , but I have no idea how to write this with those "%20", can you help me with this? Thank you very much

**Comment by AlanKvA1** [comment]
I figured out how to write. Thank you very much!

**Comment by realbadidas** [comment]
i would recommend to encode the whole script that you are trying to execute and not only the spaces.

you need to encode it with a tool like this (https://meyerweb.com/eric/tools/dencoder/)

and then press encode and paste it in the execute parameter.

**Comment by AlanKvA1** [comment]
Amazing!!! Thank you! It works
